In [1]:
import numpy as np
arr = np.random.random_sample((3,))

In [2]:
arr

array([0.54434569, 0.7515331 , 0.7799534 ])

In [12]:
b = 0.5
a = -0.5
arr1 = (b - a) * np.random.random_sample((1,10)) + a 
arr1

array([[ 0.07159255, -0.09896982, -0.20073434,  0.37236804,  0.21449664,
        -0.11609746, -0.46351703, -0.48881296, -0.15041578,  0.26149239]])

In [13]:
t = arr1.shape
t = arr1.transpose()
t

array([[ 0.07159255],
       [-0.09896982],
       [-0.20073434],
       [ 0.37236804],
       [ 0.21449664],
       [-0.11609746],
       [-0.46351703],
       [-0.48881296],
       [-0.15041578],
       [ 0.26149239]])

In [95]:
x = np.array([
    [-1, -1],
    [-1, 1],
    [1, -1],
    [1, 1]
])

# Target
y = np.array([-1, 1, 1, -1])
alpha = 0.01

In [21]:
wij = ( b - a ) * np.random.random_sample((3,2)) + a
wij.shape

(3, 2)

In [16]:
wij

array([[-0.27729942,  0.19370335],
       [-0.45751816,  0.06875761],
       [-0.41915152, -0.44829482]])

In [17]:
wjk = (b - a ) * np.random.random_sample((3,1)) + a

In [18]:
wjk

array([[0.3707429 ],
       [0.15231429],
       [0.41867803]])

In [20]:
wjk.shape

(3, 1)

In [77]:
bias_in = np.array([[1],[1]])
bias_out = np.array([1])
bias_out.shape
bias_out[0]

1

In [36]:
x.shape
bias_in.shape
bias_in[0][0]
x.shape

(4, 2)

In [47]:
xin = np.array([[bias_in[0][0], x[0][0], x[0][1]]])

In [52]:
xin = xin.transpose()
xin.shape

(3, 1)

In [68]:
z = (wij.transpose()) @ xin

In [69]:
z

array([[-0.0720294 ],
       [ 0.24628221]])

In [70]:
import math as mt
def sigmoid( mat):
    temp = mat.copy()
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            temp[i][j] = 1.0 / ( 1 + mt.exp(-mat[i][j]))
    
    return temp

In [71]:
tp = sigmoid(z)

In [72]:
tp.shape

(2, 1)

In [74]:
tp

array([[0.48200043],
       [0.56126122]])

In [100]:
zin = np.array([bias_out[0], tp[0][0], tp[1][0]])
zin = zin.reshape(3,1)

In [101]:
wjk.shape

(3, 1)

In [102]:
yin_k = (wjk.transpose()) @ zin
yin_k = yin_k.reshape(1,1)
yin_k.shape

(1, 1)

In [103]:
yk = sigmoid(yin_k)

In [104]:
yk

array([[0.66354811]])

In [105]:
del_k = ( y[0] - yk) * yk * ( 1 - yk)
del_k

array([[-0.37139047]])

In [106]:
del_wjk = alpha * del_k * zin
del_wjk.shape

(3, 1)

In [108]:
del_wjk

array([[-0.0037139 ],
       [-0.0017901 ],
       [-0.00208447]])

In [109]:
del_inj = del_k * wjk

In [110]:
del_inj

array([[-0.13769038],
       [-0.05656808],
       [-0.15549303]])

In [114]:
del_inj.shape

(3, 1)

In [115]:
zin.shape

(3, 1)

In [116]:
del_j = del_inj * zin * (1 - zin)

In [117]:
del_j

array([[-0.        ],
       [-0.01412369],
       [-0.0382897 ]])

In [118]:
del_j.shape

(3, 1)

In [119]:
del_wij = alpha * (del_j * xin)

In [120]:
del_wij

array([[-0.        ],
       [ 0.00014124],
       [ 0.0003829 ]])

In [127]:
# update
arr = np.array([del_wij, del_wij])

In [128]:
del_wij.shape

(3, 1)

In [125]:
arr1 = del_wij.reshape(1,3)

In [126]:
arr1

array([[-0.        ,  0.00014124,  0.0003829 ]])

In [131]:
arr = np.array([arr1, arr1])

In [132]:
arr.shape

(2, 1, 3)

In [135]:
wij[:][0]

array([-0.15237768,  0.35234666])