In [1]:
import numpy as np

In [15]:
# Features
x = np.array([
    [-1, -1],
    [-1, 1],
    [1, -1],
    [1, 1]
])

# Target
y = np.array([-1, 1, 1, -1])
alpha = 0.01
epoch = 1

In [11]:
# Initialization of weights (input layer)
a = -0.5
b = 0.5
wij_1 = (b - a) * np.random.random_sample((3,1)) + a
wij_2 = (b - a) * np.random.random_sample((3,1)) + a

# Bias
bias_in = np.array([1 , 1])


In [13]:
# Initialization of weights ( output layer)

wjk = ( b - a ) * np.random.random_sample((3,1)) + a

# Bias
bias_out = np.array([1])

In [14]:
import math as mt
def sigmoid( mat):
    temp = mat.copy()
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            temp[i][j] = 1.0 / ( 1 + mt.exp(-mat[i][j]))
    
    return temp

In [143]:
def display(itr):
    print(f'\n----------Iteration {itr + 1} -----------------------\n')
    print(f' Wij_1 :  \n{wij_1}')
    print(f' Wij_2 :  \n{wij_2}')
    print(f'Bias in : \n{bias_in}')

    print(f' Wjk :  \n{wjk}')
    print(f'Bias out : \n{bias_out}')
    
    print('-------------------------------------------')


In [144]:
display(0)


----------Epoch 0 -----------------------

 Wij_1 :  
[[ 0.44695317]
 [-0.19077936]
 [-0.00203458]]
 Wij_2 :  
[[-0.02239536]
 [-0.08811389]
 [ 0.12535028]]
Bias in : 
[1 1]
 Wjk :  
[[0.47923513]
 [0.20062644]
 [0.34373349]]
Bias out : 
[1]
-------------------------------------------


In [129]:
# Change the range
for epo in range(epoch):
    print(f'------------Epoch: {epo + 1}-------------')
    for i in range(x.shape[0]):

        # Required output
        tk = y[i]

        # Preparing for input
        xin_1 = np.array([[bias_in[0], x[i][0], x[i][1]]])
        xin_1 = xin_1.transpose()

        xin_2 = np.array([[bias_in[1], x[i][0], x[i][1]]])
        xin_2 = xin_2.transpose()

        # Zin_j
        Zin_1 = (wij_1.transpose()) @ xin_1
        Zin_2 = (wij_2.transpose()) @ xin_2

        # Get Zj
        Z = np.array([Zin_1[0], Zin_2[0]])
        Zj = sigmoid(Z)
        Zin = np.array([[bias_out[0], Zj[0][0], Zj[1][0]]]) 
        Zin = Zin.transpose() # For input into output neuron

        # Yin_k
        yin_k = (wjk.transpose()) @ Zin
        yk = sigmoid(yin_k)

        # del_k
        del_k = (tk - yk) * yk * (1 - yk)

        # del_wjk
        del_wjk = alpha * del_k * Zin

        # del_in_j
        del_inj = del_k * wjk
        del_j = del_inj * Zin * ( 1 - Zin)

        #del_Wij
        del_wij = alpha * (del_j * xin)

        # Update
        wij_1 = wij_1 + del_wij
        wij_2 = wij_2 + del_wij

        wjk = wjk + del_wjk
        
        display()

