In [193]:
import numpy as np
from matplotlib import pyplot as plt

In [232]:
# Features
x = np.array([
    [-1, -1],
    [-1, 1],
    [1, -1],
    [1, 1]
])

# Target
y = np.array([-1, 1, 1, -1])
alpha = 0.001
epoch = 1400

In [248]:
# Initialization of weights (input layer)
a = -0.5
b = 0.5
# [
#  [w10, w11, w12],
#  [w20, w21, w22]
# ]
wij = (b - a) * np.random.random_sample((2,3)) + a

# Bias
bias_in = np.array([1 , 1])
wij

array([[ 0.4955771 , -0.21721174,  0.33491905],
       [ 0.22801403, -0.00361701, -0.21270055]])

In [249]:
# Initialization of weights ( output layer)
# [
#   [w10, w11, w12 ]
# ]
wjk = ( b - a ) * np.random.random_sample((1,3)) + a

# Bias
bias_out = np.array([1])
wjk

array([[-0.2918508 ,  0.26999404,  0.07115485]])

In [250]:
def sigmoid(mat):
    return ((1.0) / (1 + np.exp(-mat)))

In [251]:
def display(itr):
    print(f'\n----------Iteration {itr + 1} -------------------\n')
    print(f' Wij :  \n{wij} \n')
    print(f'Bias in : {bias_in}\n')

    print(f' Wjk :  \n{wjk}\n')
    print(f'Bias out : {bias_out}\n')

In [252]:
print("Initialization......")
display(0)

Initialization......

----------Iteration 1 -------------------

 Wij :  
[[ 0.4955771  -0.21721174  0.33491905]
 [ 0.22801403 -0.00361701 -0.21270055]] 

Bias in : [1 1]

 Wjk :  
[[-0.2918508   0.26999404  0.07115485]]

Bias out : [1]



In [253]:
for epo in range(epoch):
    print(f'------------Epoch: {epo + 1}-------------')
    for i in range(x.shape[0]):

        # Required output
        tk = y[i]

        # Preparing for input
        xin = np.array([[bias_in[0], x[i][0], x[i][1]]])
        xin = xin.transpose()
        # print(f'xin : {xin}')

        # Zin_j       
        Zin = wij @ xin
        
        # Get Zj
        Zj = sigmoid(Zin)
        # print(f'Zin : {Zin}')
        # print(f'Zj: {Zj}')
        
        Z = np.array([[bias_out[0], Zj[0][0], Zj[1][0]]]) 
        Z = Z.transpose() # For input into output neuron

        # Yin_k
        yin_k = wjk @ Z
        # print(f'Yin_k : {yin_k}')
        yk = sigmoid(yin_k)
        # print(f'Yk : {yk}')

        # del_k
        del_k = (tk - yk) * yk * (1 - yk)
        err_ho.append(del_k[0][0])
        # print(f'del_k : {del_k}')

        # del_wjk
        del_wjk = alpha * ( del_k @ (Z.transpose()))
        # print(f'del_wjk : {del_wjk}')

        # del_in_j
        t_wjk = np.array([[wjk[0][1], wjk[0][2]]]) # improve
        t_wjk = t_wjk.transpose()
        del_inj = t_wjk @ del_k
        # print(f'del_inj : {del_inj}')
        
        del_j = del_inj * Zin * ( 1 - Zin)
        # print(f'del_j : {del_j}')

        #del_Wij
        del_wij = alpha * (del_j @ (xin.transpose()))
        #print(f'del_wij : {del_wij}')
                           

        # Update
        wij += del_wij
        wjk += del_wjk
        
        display(i)



------------Epoch: 1-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.49555369 -0.21718834  0.33494246]
 [ 0.22800755 -0.00361053 -0.21269407]] 

Bias in : [1 1]

 Wjk :  
[[-0.29221957  0.26977523  0.07093016]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.49555196 -0.21718661  0.33494073]
 [ 0.22800772 -0.0036107  -0.21269391]] 

Bias in : [1 1]

 Wjk :  
[[-0.29209113  0.26987031  0.07099499]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.49554983 -0.21718873  0.33494286]
 [ 0.22801003 -0.00360839 -0.21269621]] 

Bias in : [1 1]

 Wjk :  
[[-0.29195923  0.2699344   0.07107513]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.49552619 -0.21721238  0.33491921]
 [ 0.22800972 -0.0036087  -0.21269651]] 

Bias in : [1 1]

 Wjk :  
[[-0.29232856  0.26969482  0.07088938]]

Bias out : [1]

------------Epoch: 2-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.495502


Bias in : [1 1]

 Wjk :  
[[-0.32347337  0.25020686  0.05356516]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.49225752 -0.21726699  0.33493279]
 [ 0.22776062 -0.00312305 -0.21246372]] 

Bias in : [1 1]

 Wjk :  
[[-0.32383833  0.24997038  0.05338157]]

Bias out : [1]

------------Epoch: 69-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.49223619 -0.21724566  0.33495411]
 [ 0.22775582 -0.00311826 -0.21245892]] 

Bias in : [1 1]

 Wjk :  
[[-0.32420252  0.24975457  0.05315975]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.49223467 -0.21724414  0.33495259]
 [ 0.22775595 -0.00311838 -0.21245879]] 

Bias in : [1 1]

 Wjk :  
[[-0.32407091  0.24985193  0.05322616]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.49223253 -0.21724628  0.33495473]
 [ 0.22775771 -0.00311662 -0.21246056]] 

Bias in : [1 1]

 Wjk :  
[[-0.32393626  0.24991724  0.05330797]]

Bias out : [1]


----------It


 Wij :  
[[ 0.4894991  -0.21731342  0.33496795]
 [ 0.22759513 -0.00279651 -0.21230946]] 

Bias in : [1 1]

 Wjk :  
[[-0.35189362  0.23245169  0.03776799]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.48949698 -0.21731554  0.33497007]
 [ 0.2275964  -0.00279524 -0.21231073]] 

Bias in : [1 1]

 Wjk :  
[[-0.35175676  0.23251797  0.03785114]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.48947698 -0.21733554  0.33495007]
 [ 0.22759623 -0.0027954  -0.2123109 ]] 

Bias in : [1 1]

 Wjk :  
[[-0.3521174   0.23228453  0.0376697 ]]

Bias out : [1]

------------Epoch: 131-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.48945746 -0.21731603  0.33496959]
 [ 0.22759289 -0.00279206 -0.21230755]] 

Bias in : [1 1]

 Wjk :  
[[-0.35247714  0.2320716   0.03745065]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.4894561  -0.21731467  0.33496823]
 [ 0.22759298 -0.00279215 -0.21230746]] 

Bias 


Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.48635599 -0.21742041  0.33499482]
 [ 0.22747335 -0.00254454 -0.21219691]] 

Bias in : [1 1]

 Wjk :  
[[-0.38571044  0.21130127  0.0189874 ]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.48633805 -0.21743835  0.33497688]
 [ 0.22747327 -0.00254463 -0.212197  ]] 

Bias in : [1 1]

 Wjk :  
[[-0.38606542  0.21107175  0.01880878]]

Bias out : [1]

------------Epoch: 208-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.48632066 -0.21742096  0.33499427]
 [ 0.22747162 -0.00254298 -0.21219535]] 

Bias in : [1 1]

 Wjk :  
[[-0.38641934  0.21086253  0.01859332]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.4863195  -0.2174198   0.33499311]
 [ 0.22747167 -0.00254303 -0.21219531]] 

Bias in : [1 1]

 Wjk :  
[[-0.38628225  0.21096378  0.01866248]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.48631743 -0.21742187 


------------Epoch: 285-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.48351649 -0.21753867  0.33502373]
 [ 0.22743181 -0.00245862 -0.21215866]] 

Bias in : [1 1]

 Wjk :  
[[-0.41907716  0.19047297  0.00044976]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.4835155  -0.21753767  0.33502273]
 [ 0.22743181 -0.00245862 -0.21215866]] 

Bias in : [1 1]

 Wjk :  
[[-0.4189376   0.19057598  0.00052016]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.48351351 -0.21753966  0.33502472]
 [ 0.22743183 -0.0024586  -0.21215867]] 

Bias in : [1 1]

 Wjk :  
[[-0.41879617  0.19064425  0.00060609]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.48349755 -0.21755562  0.33500877]
 [ 0.22743182 -0.00245861 -0.21215868]] 

Bias in : [1 1]

 Wjk :  
[[-0.41914518  0.19041883  0.00043047]]

Bias out : [1]

------------Epoch: 286-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.4


 Wjk :  
[[-0.4472719   0.17288158 -0.01521444]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.48127125 -0.21764899  0.33505213]
 [ 0.22745809 -0.00251565 -0.21218318]] 

Bias in : [1 1]

 Wjk :  
[[-0.44713044  0.17298593 -0.01514308]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.48126935 -0.21765088  0.33505402]
 [ 0.22745755 -0.00251618 -0.21218265]] 

Bias in : [1 1]

 Wjk :  
[[-0.44698743  0.17305489 -0.01505619]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.48125507 -0.21766517  0.33503973]
 [ 0.22745762 -0.00251611 -0.21218259]] 

Bias in : [1 1]

 Wjk :  
[[-0.44733101  0.17283316 -0.01522908]]

Bias out : [1]

------------Epoch: 355-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.48124138 -0.21765148  0.33505342]
 [ 0.2274589  -0.0025174  -0.21218387]] 

Bias in : [1 1]

 Wjk :  
[[-0.4476732   0.17263127 -0.01543739]]

Bias out : [1]


----------Iteration 2 ------


 Wij :  
[[ 0.47915858 -0.21776819  0.33508493]
 [ 0.22754268 -0.00270514 -0.21226203]] 

Bias in : [1 1]

 Wjk :  
[[-0.47588452  0.15505524 -0.03111856]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.4791568  -0.21776996  0.3350867 ]
 [ 0.22754158 -0.00270625 -0.21226092]] 

Bias in : [1 1]

 Wjk :  
[[-0.47574011  0.15512478 -0.03103082]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.47914419 -0.21778257  0.33507409]
 [ 0.22754171 -0.00270612 -0.21226079]] 

Bias in : [1 1]

 Wjk :  
[[-0.47607786  0.15490698 -0.03120076]]

Bias out : [1]

------------Epoch: 428-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.47913217 -0.21777054  0.33508612]
 [ 0.22754429 -0.00270871 -0.21226338]] 

Bias in : [1 1]

 Wjk :  
[[-0.47641407  0.15470879 -0.03140546]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.47913144 -0.21776981  0.33508539]
 [ 0.22754421 -0.00270863 -0.21226346]] 

Bias 


Bias in : [1 1]

 Wjk :  
[[-0.50375418  0.13765592 -0.04657831]]

Bias out : [1]

------------Epoch: 501-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.4772772  -0.21788729  0.3351194 ]
 [ 0.22768127 -0.00302541 -0.21239169]] 

Bias in : [1 1]

 Wjk :  
[[-0.50408438  0.13746141 -0.0467794 ]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.47727658 -0.21788667  0.33511878]
 [ 0.22768115 -0.00302528 -0.21239181]] 

Bias in : [1 1]

 Wjk :  
[[-0.5039398   0.13756796 -0.04670644]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.47727495 -0.2178883   0.33512041]
 [ 0.22767948 -0.00302696 -0.21239014]] 

Bias in : [1 1]

 Wjk :  
[[-0.50379423  0.13763799 -0.046618  ]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.47726394 -0.21789931  0.3351094 ]
 [ 0.22767967 -0.00302677 -0.21238995]] 

Bias in : [1 1]

 Wjk :  
[[-0.50412604  0.13742418 -0.04678493]]

Bias out : [1]

------------


 Wij :  
[[ 0.4756393  -0.218001    0.33515356]
 [ 0.22786378 -0.00346905 -0.21256442]] 

Bias in : [1 1]

 Wjk :  
[[-0.53078646  0.12081872 -0.06161599]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.47562979 -0.2180105   0.33514406]
 [ 0.22786402 -0.00346881 -0.21256418]] 

Bias in : [1 1]

 Wjk :  
[[-0.53111234  0.12060886 -0.06177989]]

Bias out : [1]

------------Epoch: 576-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.47562081 -0.21800151  0.33515305]
 [ 0.22786896 -0.00347375 -0.21256913]] 

Bias in : [1 1]

 Wjk :  
[[-0.53143637  0.12041811 -0.06197729]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.47562029 -0.21800099  0.33515253]
 [ 0.22786879 -0.00347359 -0.21256929]] 

Bias in : [1 1]

 Wjk :  
[[-0.53129062  0.12052547 -0.06190373]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.47561881 -0.21800247  0.335154  ]
 [ 0.22786656 -0.00347582 -0.21256706]] 

Bias 


 Wij :  
[[ 0.47415741 -0.21811883  0.33517876]
 [ 0.22810164 -0.00405811 -0.21279166]] 

Bias in : [1 1]

 Wjk :  
[[-0.55845254  0.10357699 -0.07697245]]

Bias out : [1]

------------Epoch: 654-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.47414986 -0.21811128  0.33518632]
 [ 0.22810767 -0.00406415 -0.2127977 ]] 

Bias in : [1 1]

 Wjk :  
[[-0.5587702   0.10339009 -0.07716605]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.47414943 -0.21811085  0.33518589]
 [ 0.22810746 -0.00406394 -0.21279792]] 

Bias in : [1 1]

 Wjk :  
[[-0.55862353  0.10349811 -0.077092  ]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.47414813 -0.21811215  0.33518719]
 [ 0.22810467 -0.00406673 -0.21279513]] 

Bias in : [1 1]

 Wjk :  
[[-0.55847632  0.1035688  -0.07700257]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.47414013 -0.21812015  0.33517919]
 [ 0.22810494 -0.00406645 -0.21279485]] 

Bias 


Bias in : [1 1]

 Wjk :  
[[-0.58355075  0.08797137 -0.0909444 ]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.47297513 -0.21820557  0.33521611]
 [ 0.22836549 -0.00473695 -0.21304894]] 

Bias in : [1 1]

 Wjk :  
[[-0.58340307  0.08804224 -0.09085469]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.47296845 -0.21821225  0.33520943]
 [ 0.22836579 -0.00473666 -0.21304864]] 

Bias in : [1 1]

 Wjk :  
[[-0.58371682  0.08784038 -0.0910124 ]]

Bias out : [1]

------------Epoch: 729-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.47296217 -0.21820597  0.33521571]
 [ 0.2283728  -0.00474366 -0.21305565]] 

Bias in : [1 1]

 Wjk :  
[[-0.58402844  0.08765713 -0.0912024 ]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.47296182 -0.21820563  0.33521536]
 [ 0.22837253 -0.0047434  -0.21305591]] 

Bias in : [1 1]

 Wjk :  
[[-0.58388111  0.0877656  -0.091128  ]]

Bias out : [1]


----------I


 Wjk :  
[[-0.60864501  0.0723243  -0.1048831 ]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.47197039 -0.21828922  0.33524183]
 [ 0.22867093 -0.00553657 -0.2133519 ]] 

Bias in : [1 1]

 Wjk :  
[[-0.60849722  0.07243308 -0.10480843]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.47196945 -0.21829017  0.33524278]
 [ 0.22866711 -0.00554039 -0.21334809]] 

Bias in : [1 1]

 Wjk :  
[[-0.60834922  0.07250406 -0.10471854]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.47196404 -0.21829557  0.33523737]
 [ 0.22866743 -0.00554008 -0.21334778]] 

Bias in : [1 1]

 Wjk :  
[[-0.60865702  0.07230611 -0.10487319]]

Bias out : [1]

------------Epoch: 806-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.47195898 -0.21829051  0.33524243]
 [ 0.22867535 -0.005548   -0.2133557 ]] 

Bias in : [1 1]

 Wjk :  
[[-0.60896255  0.07212651 -0.10505958]]

Bias out : [1]


----------Iteration 2 ------


 Wij :  
[[ 0.47120634 -0.21835694  0.3352637 ]
 [ 0.2289812  -0.0063917  -0.21366573]] 

Bias in : [1 1]

 Wjk :  
[[-0.63140489  0.05814707 -0.11753278]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.47120612 -0.21835672  0.33526348]
 [ 0.22898083 -0.00639133 -0.2136661 ]] 

Bias in : [1 1]

 Wjk :  
[[-0.63125685  0.05825602 -0.11745795]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.47120535 -0.21835749  0.33526425]
 [ 0.22897656 -0.00639561 -0.21366182]] 

Bias in : [1 1]

 Wjk :  
[[-0.63110872  0.05832703 -0.11736798]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.47120108 -0.21836176  0.33525998]
 [ 0.22897687 -0.0063953  -0.21366151]] 

Bias in : [1 1]

 Wjk :  
[[-0.63141098  0.0581327  -0.11751979]]

Bias out : [1]

------------Epoch: 879-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.47119709 -0.21835778  0.33526397]
 [ 0.22898559 -0.00640402 -0.21367023]] 

Bias 


 Wij :  
[[ 0.47058598 -0.21841426  0.33528243]
 [ 0.22932285 -0.00738997 -0.21402191]] 

Bias in : [1 1]

 Wjk :  
[[-0.65422062  0.04392838 -0.13021408]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.47058282 -0.21841742  0.33527928]
 [ 0.22932315 -0.00738967 -0.21402161]] 

Bias in : [1 1]

 Wjk :  
[[-0.65451718  0.04373776 -0.13036294]]

Bias out : [1]

------------Epoch: 956-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.47057988 -0.21841448  0.33528222]
 [ 0.22933264 -0.00739916 -0.2140311 ]] 

Bias in : [1 1]

 Wjk :  
[[-0.6548112   0.04356501 -0.13054254]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.47057972 -0.21841432  0.33528206]
 [ 0.22933221 -0.00739873 -0.21403153]] 

Bias in : [1 1]

 Wjk :  
[[-0.65466306  0.04367402 -0.13046762]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.47057914 -0.2184149   0.33528264]
 [ 0.22932746 -0.00740348 -0.21402677]] 

Bias 


------------Epoch: 1030-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.47015531 -0.21845491  0.33529515]
 [ 0.22968109 -0.00843903 -0.21440397]] 

Bias in : [1 1]

 Wjk :  
[[-0.67618804  0.03024423 -0.14242494]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.4701552  -0.2184548   0.33529504]
 [ 0.2296806  -0.00843854 -0.21440446]] 

Bias in : [1 1]

 Wjk :  
[[-0.67603994  0.03035319 -0.14235002]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.47015479 -0.2184552   0.33529544]
 [ 0.22967542 -0.00844372 -0.21439928]] 

Bias in : [1 1]

 Wjk :  
[[-0.67589194  0.0304241  -0.14226015]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.47015265 -0.21845735  0.33529329]
 [ 0.2296757  -0.00844344 -0.214399  ]] 

Bias in : [1 1]

 Wjk :  
[[-0.67618309  0.03023699 -0.14240622]]

Bias out : [1]

------------Epoch: 1031-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0


 Wij :  
[[ 0.46990401 -0.21847981  0.335303  ]
 [ 0.22999989 -0.00945174 -0.21475715]] 

Bias in : [1 1]

 Wjk :  
[[-0.69458407  0.01877296 -0.1526507 ]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.46990271 -0.21848111  0.3353017 ]
 [ 0.23000014 -0.00945149 -0.2147569 ]] 

Bias in : [1 1]

 Wjk :  
[[-0.6948705   0.01858889 -0.15279433]]

Bias out : [1]

------------Epoch: 1098-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.4699015  -0.21847991  0.3353029 ]
 [ 0.23001088 -0.00946224 -0.21476764]] 

Bias in : [1 1]

 Wjk :  
[[-0.69515416  0.01842228 -0.15296783]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.46990144 -0.21847984  0.33530284]
 [ 0.23001034 -0.00946169 -0.21476819]] 

Bias in : [1 1]

 Wjk :  
[[-0.69500623  0.01853112 -0.15289294]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.46990119 -0.21848009  0.33530308]
 [ 0.23000478 -0.00946725 -0.21476263]] 

Bias


 Wij :  
[[ 0.46976509 -0.21849406  0.33530685]
 [ 0.23036547 -0.01063371 -0.21517382]] 

Bias in : [1 1]

 Wjk :  
[[-0.71453203  0.00633471 -0.16373973]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.46976466 -0.2184945   0.33530642]
 [ 0.23036568 -0.0106335  -0.21517362]] 

Bias in : [1 1]

 Wjk :  
[[-0.7148134   0.00615391 -0.16388074]]

Bias out : [1]

------------Epoch: 1172-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.46976427 -0.21849411  0.33530681]
 [ 0.230377   -0.01064482 -0.21518494]] 

Bias in : [1 1]

 Wjk :  
[[-0.71509187  0.00599036 -0.16405119]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.46976425 -0.21849408  0.33530679]
 [ 0.23037639 -0.01064421 -0.21518555]] 

Bias in : [1 1]

 Wjk :  
[[-0.71494422  0.00609898 -0.16397641]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.46976416 -0.21849417  0.33530687]
 [ 0.23037045 -0.01065015 -0.2151796 ]] 

Bias


Bias in : [1 1]

 Wjk :  
[[-0.73407779 -0.00585315 -0.17460573]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.46976188 -0.21849524  0.33530609]
 [ 0.23074186 -0.01187701 -0.21561813]] 

Bias in : [1 1]

 Wjk :  
[[-0.73393051 -0.0057448  -0.1745311 ]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.46976196 -0.21849517  0.33530602]
 [ 0.23073555 -0.01188332 -0.21561182]] 

Bias in : [1 1]

 Wjk :  
[[-0.73378344 -0.00567435 -0.17444184]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.46976234 -0.21849479  0.3353064 ]
 [ 0.23073571 -0.01188316 -0.21561167]] 

Bias in : [1 1]

 Wjk :  
[[-0.73405988 -0.00585199 -0.17458028]]

Bias out : [1]

------------Epoch: 1246-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.4697627  -0.21849515  0.33530603]
 [ 0.23074756 -0.01189501 -0.21562352]] 

Bias in : [1 1]

 Wjk :  
[[-0.73433332 -0.00601259 -0.17474779]]

Bias out : [1]


----------


Bias in : [1 1]

 Wjk :  
[[-0.75239773 -0.01729667 -0.18477484]]

Bias out : [1]

------------Epoch: 1319-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.4698855  -0.21848386  0.3353008 ]
 [ 0.23111466 -0.01319046 -0.21607605]] 

Bias in : [1 1]

 Wjk :  
[[-0.75266635 -0.01745444 -0.18493952]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.46988556 -0.21848392  0.33530087]
 [ 0.23111391 -0.01318972 -0.2160768 ]] 

Bias in : [1 1]

 Wjk :  
[[-0.75251953 -0.01734643 -0.18486508]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.46988579 -0.21848369  0.33530064]
 [ 0.23110725 -0.01319637 -0.21607014]] 

Bias in : [1 1]

 Wjk :  
[[-0.75237294 -0.01727621 -0.18477612]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.46988693 -0.21848255  0.33530177]
 [ 0.23110735 -0.01319628 -0.21607005]] 

Bias in : [1 1]

 Wjk :  
[[-0.75264461 -0.01745079 -0.18491209]]

Bias out : [1]

-----------


 Wjk :  
[[-0.76889992 -0.02759625 -0.19396381]]

Bias out : [1]


----------Iteration 4 -------------------

 Wij :  
[[ 0.47010625 -0.21846084  0.33529365]
 [ 0.23144799 -0.01445552 -0.21650849]] 

Bias in : [1 1]

 Wjk :  
[[-0.76916734 -0.02776811 -0.19409755]]

Bias out : [1]

------------Epoch: 1388-------------

----------Iteration 1 -------------------

 Wij :  
[[ 0.47010793 -0.21846252  0.33529197]
 [ 0.23146074 -0.01446827 -0.21652124]] 

Bias in : [1 1]

 Wjk :  
[[-0.76943153 -0.0279233  -0.19425966]]

Bias out : [1]


----------Iteration 2 -------------------

 Wij :  
[[ 0.47010803 -0.21846262  0.33529207]
 [ 0.23145993 -0.01446745 -0.21652205]] 

Bias in : [1 1]

 Wjk :  
[[-0.76928522 -0.02781565 -0.19418542]]

Bias out : [1]


----------Iteration 3 -------------------

 Wij :  
[[ 0.47010839 -0.21846225  0.3352917 ]
 [ 0.23145296 -0.01447442 -0.21651508]] 

Bias in : [1 1]

 Wjk :  
[[-0.76913912 -0.02774566 -0.19409679]]

Bias out : [1]


----------Iteration 4 -----

In [254]:
# Prediction XOR Gate
for j in range(x.shape[0]):
    
    xin = np.array([[bias_in[0], x[j][0], x[j][1]]])
    xin = xin.transpose()    
    Zin = wij @ xin 
    Zj = sigmoid(Zin)
    Z = np.array([[bias_out[0], Zj[0][0], Zj[1][0]]]) 
    Z = Z.transpose() # For input into output neuron
    yin_k = wjk @ Z
    yk = sigmoid(yin_k)
    print(yk)
    print(xin[1][0], ' ' , xin[2][0], ' ', yk[0][0]>0.5)


[[0.28702266]]
-1   -1   False
[[0.2903916]]
-1   1   False
[[0.28796222]]
1   -1   False
[[0.29125857]]
1   1   False
